### ISSUE TITLE
Km si Price Range trebuie sa fie dinamice. Contin start si end .. vreau range de la 0 la 100. Tu configurezi in serviciu cat de mare e range-ul

### ISSUE THREAD

**Issue by stefanbulzan** [nomak8702/Homework-Github#2]
https://github.com/nomak8702/Homework-Github/blob/00dada402e9c30be80e1283d387eaaa9d503efd8/src/curs12/extraExercise/KmRange.java#L4

**Comment by nomak8702** [comment]
Nu stiu cum trebuie sa arate rezultat...
cum sa grupez masinile
